### ISSUE TITLE
Add oci run sub command

### ISSUE THREAD

**Issue by nirs** [nirs/oci#10]
Use case:
- Run custom build stages like new network integration tests:
  https://gerrit.ovirt.org/c/98187/

Example usage:

    oci run --stage network-integ CHANGE_NUMBER

The command should build one or more stages using jenkins.run(), and watch the build until it completes.

Complications:
- jenkins.run() accept only single stage now, need to change ti to accept multiple stages.
- Need to check how to pass multiple stages to jenkins. If there is no way to do it, we can support only one stage for now.

**Comment by nirs** [comment]
@Funkabell I guess you own this issue.

**Comment by bell-lev** [comment]
@nirs ,I have checked with Daniel Belenky, and there is not such option.

Just to make sure what option i am referring to, is inputting into the jenkins job build, a number of stages (e.g. "check-patch,build-artifacts"). This is not possible.

So we'll be supporting only on stage?

**Comment by nirs** [comment]
If STD_CI_STAGE can accept only one stage, we will have to run multiple jobs to build multiple stages.

We can accept multiple stages in the command, run multiple jobs on jenkins, and wait for all of them, but this sounds like work for future version.

So lets open an issue for multiple stages and add a simple and stupid run command.

**Comment by bell-lev** [comment]
Yes, that's what i meant, STD_CI_STAGE accepts only one parameter.

Regarding the script accepting several arguments - I think it'll might make more sense to just run the oci script several times, no?

Will the oci run all stages at once, or one followed by the other?

If you intend on running them at the same time (which makes sense efficiency-wise), I can't imagine how the output will look. Seeing all progresses on all of the jobs might look confusing. I think running every job, and watching the output in - say, different windows (user manually starts oci script per job), would be more organized. Don't you think?

**Comment by nirs** [comment]
Supporting concurent jobs is a UI challenge, this is why I suggest to defer it to another issue.
