### ISSUE TITLE
Replace configuration code with new config module

### ISSUE THREAD

**Issue by nirs** [nirs/oci#18]
build-artifacts.py and system-tests.py duplicate configuration code. They should use the new config modules added in #16 

- https://github.com/nirs/oci/blob/857f949d17dcd6b3cd985abe1b55aa3c6444affc/build-artifacts.py#L18
- https://github.com/nirs/oci/blob/857f949d17dcd6b3cd985abe1b55aa3c6444affc/system-tests.py#L25

@Funkabell do you want to take this?

**Comment by bell-lev** [comment]
@nirs yes good point, will do!
