### ISSUE TITLE
Add command line tool

### ISSUE THREAD

**Issue by nirs** [nirs/oci#4]
The tool should start with this sub command:

- oci build-artifacts CHANGE
  Start build-artifacts using jenknins.run() and watch the job until it completes.

Gloabl options:
- --verbose - enable debug log

**Comment by bell-lev** [comment]
@nirs Just a small clarification, do you want to run **the** build_artifacts.py, or the same flow as in build_artifacts.py?

**Comment by nirs** [comment]
I think we should run the same flow as build_artifacts.py, and delete that file.
