### ISSUE TITLE
Wrong custom repo URL in system tests

### ISSUE THREAD

**Issue by vjuranek** [nirs/oci#50]
System tests build a repo based on provided patch number first. The result is set of artifacts with custom rpm repo(s). The URL of Jenkins job which built the repo is passed as a `custom_repos` parameter to `ovirt-system-tests_manual`. However, this jobs fails with error, unable to read the repo as the repo is expected to be on provided URL:

```
STDERR
16:48:06 b"Errors during downloading metadata for repository 'extra-src-0':\n  - Status code: 404 for https://jenkins.ovirt.org/job/standard-manual-runner/1680/repodata/repomd.xml (IP: 66.187.230.92)\nError: Failed to download metadata for repo 'extra-src-0': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried\n"
16:48:06     * STDERR
16:48:06 b"Errors during downloading metadata for repository 'extra-src-0':\n  - Status code: 404 for https://jenkins.ovirt.org/job/standard-manual-runner/1680/repodata/repomd.xml (IP: 66.187.230.92)\nError: Failed to download metadata for repo 'extra-src-0': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried\n"
16:48:06   # [Thread-2] Deploy VM lago-basic-suite-master-host-0: ERROR (in 0:00:11)
```

One need to provide direct URL of the repo, e.g. https://jenkins.ovirt.org/job/standard-manual-runner/1680/artifact/build-artifacts.build-py3.el8.x86_64/ . As the code of ovirt-ci hasn't changed for quite some time and it worked in the passed, probably configuration of `ovirt-system-tests_manual` has changed.

**Comment by vjuranek** [comment]
As the job usually builds multiple repos for various architectures and there's no unified name (e.g. for vdsm x86_64 repo is on `build-artifacts.build-py3.el8.x86_64` while for engine it's `check-patch.el8.x86_64`), it cannot be solved by hardcoding the relative path. What should work is to provide all top level dirs in built artifacts - repos for irrelevant architectures are ignored.

**Comment by nirs** [comment]
System tests used to work with the build url:
https://jenkins.ovirt.org/job/standard-manual-runner/1680/

There was no need to pass the direct URL:
https://jenkins.ovirt.org/job/standard-manual-runner/1680/artifact/build-artifacts.build-py3.el8.x86_64/

This looks like regression in system tests job. Pleas file ovirt-infra bug about it. Sending
mail to infra-support@ovirt.org should file a new bug.

**Comment by vjuranek** [comment]
I've send the email, but don't see any new ticket (and also don't see any such list on https://lists.ovirt.org/archives/), so create ticket manually: https://ovirt-jira.atlassian.net/browse/OVIRT-3085

**Comment by vjuranek** [comment]
Issue was acked and should be fixed in the future. However, I'd keep this issue open until it's fixed in OST for the reference (e.g. if someone else want to report it for ovirt-ci).

**Comment by nirs** [comment]
Sure, thanks @vjuranek!
